import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import RegisterModal from './components/modals/RegisterModal'
import ClientOnly from './components/ClientOnly'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Arinbn',
  description: 'Generated by Baher Keshavarz',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
         <ClientOnly>
            <Navbar/>
            <RegisterModal/>
         </ClientOnly>
        {children}
       </body>
    </html>
  )
}
