import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import RegisterModal from './components/modals/RegisterModal'
import ClientOnly from './components/ClientOnly'
import ToasterProvider from './components/providers/ToasterProvider'
import LoginModal from './components/modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import Catergories from './components/navbar/Catergories'
import RentModal from './components/modals/RentModal'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Arinbn',
  description: 'Generated by Baher Keshavarz',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();
  
  return (
    <html lang="en">
      <body className={nunito.className}>
         <ClientOnly>
            <ToasterProvider/>
            <Navbar currentUser={currentUser}/>
            <LoginModal/>
            <RentModal/>
            <RegisterModal/>
         </ClientOnly>
        {children}
       </body>
    </html>
  )
}
